spring:
  datasource:
    username: postgres
    password: sa
    url: jdbc:postgresql://localhost:5432/todolist
todolist:
  log: console # или можно json
  mail:
    username: test@notexisting.qwe
    password: