name: Тесты

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: todolist
          POSTGRES_PASSWORD: sa
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2
      - name: Установка JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Сборка и тестирование программы
        run: |
          ./gradlew update
          ./gradlew build